  language: python
  python:
    - "3.6"
  before_install:
    - sudo apt-get install portaudio19-dev
  install: python3.6 -m pip install -r requirements.txt
  script:
    - python3.6 notes2cards.py --inputFile ./test/test_file.md --deckName Docker_Deck --outputFile ./test/docker_deck.apkg
